{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "aton-service-client-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: aton-service-client-secrets
type: Opaque
data:
  config_username: {{ .Values.global.enav_service.cloud_config.username | default "" | b64enc | quote }}
  config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | b64enc | quote }}
  keystore:  {{ .Values.global.aton_service_client.keystore | default "" | quote }}
  truststore:  {{ .Values.global.aton_service_client.truststore | default "" | quote }}
{{- end }}