{{- if .Values.serviceAccount.create -}}
{{- $serviceAccountName := include "enav.serviceAccountName" . -}}
{{- if not (lookup "v1" "ServiceAccount" "$.Release.Namespace" $serviceAccountName) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enav.serviceAccountName" . }}
  labels:
    {{- include "enav.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}