{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "ckeeper-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: ckeeper-secrets
type: Opaque
data:
  config_username: {{ .Values.global.enav_service.cloud_config.username | default "" | quote }}
  config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | quote }}
  keystore:  {{ .Values.global.ckeeper.keystore | default "" | quote }}
  truststore:  {{ .Values.global.ckeeper.truststore | default "" | quote }}
{{- end }}