apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  config_endpoint: {{ .Values.global.enav_service.cloud_config.url | quote }}
  config_branch: {{ .Values.global.enav_service.cloud_config.branch | quote }}
  config_repo_url: {{ .Values.global.eureka.config_repo.url | quote }}
  config_repo_branch: {{ .Values.global.eureka.config_repo.branch | quote }}
