{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "eureka-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: eureka-secrets
type: Opaque
data:
  config_username: {{ .Values.global.enav_service.cloud_config.username | default "" |  b64enc | quote }}
  config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | b64enc | quote }}
  config_encryption_key: {{ .Values.global.enav_service.cloud_config.encryption_key | default "" | b64enc | quote }}
  config_repo_username: {{ .Values.global.eureka.config_repo.username | default "" |  b64enc | quote }}
  config_repo_password: {{ .Values.global.eureka.config_repo.password | default "" |  b64enc | quote }}
  keystore:  {{ .Values.global.eureka.keystore | default "" | quote }}
  truststore:  {{ .Values.global.eureka.truststore | default "" | quote }}
{{- end }}