{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "api-gateway-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
type: Opaque
data:
  config_username: {{ .Values.global.enav_service.cloud_config.username | default "" | b64enc | quote }}
  config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | b64enc | quote }}
  keystore:  {{ .Values.global.api_gateway.keystore | default "" | quote }}
  truststore:  {{ .Values.global.api_gateway.truststore | default "" | quote }}
{{- end }}