apiVersion: v1
kind: ConfigMap
metadata:
  name: msg-broker-config
data:
  config_endpoint: {{ .Values.global.enav_service.cloud_config.url | quote }}
  config_branch: {{ .Values.global.enav_service.cloud_config.branch | quote }}
