{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "msg-broker-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: msg-broker-secrets
type: Opaque
data:
  config_username: {{ .Values.global.enav_service.cloud_config.username | default "" | b64enc | quote }}
  config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | b64enc | quote }}
  keystore:  {{ .Values.global.msg_broker.keystore | default "" | quote }}
  truststore:  {{ .Values.global.msg_broker.trustore | default "" | quote }}
{{- end }}