{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "vdes-controller-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: vdes-controller-secrets
type: Opaque
data:
  config_username: {{ .Values.global.enav_service.cloud_config.username | default "" | b64enc | quote }}
  config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | b64enc | quote }}
  keystore:  {{ .Values.global.vdes_controller.keystore | default "" | quote }}
  truststore:  {{ .Values.global.vdes_controller.truststore | default "" | quote }}
{{- end }}