{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "vdes-controller-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: vdes-controller-secrets
type: Opaque
data:
  enav_cloud_config_username: {{ .Values.global.enav_service.cloud_config.username | default "" | quote }}
  enav_cloud_config_password: {{ .Values.global.enav_service.cloud_config.password | default "" | quote }}
  keystore:  {{ .Values.global.vdes_controller.keystore | default "" | quote }}
  truststore:  {{ .Values.global.vdes_controller.truststore | default "" | quote }}
{{- end }}