{{- if .Values.serviceAccount.create -}}
{{- $serviceAccountName := include "vdes-controller.serviceAccountName" . -}}
{{- if not (lookup "v1" "ServiceAccount" "$.Release.Namespace" $serviceAccountName) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vdes-controller.serviceAccountName" . }}
  labels:
    {{- include "vdes-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}